### ISSUE TITLE
建立汉字库

### ISSUE THREAD

**Issue by zzzjy88** [yeying-community/yeying-next#11]
建立汉字库，包含2000-3000常用汉字，形成一篇文档，便于其他人进行日常维护

**Comment by zjlzlr** [comment]
项目已修改,文档参考:
https://yeying-dev.yuque.com/af1i1w/project_doc/skr7zac1t70elq5x

**Comment by zzzjy88** [comment]
> 文档里需要完善，怎么在汉字库里添加或者删除？[Font Compress](https://www.mainww.com/#)网站/插件如何本地使用？
> ![image](https://private-user-images.githubusercontent.com/161598240/391845515-fbb4b8a8-cb0b-499c-a863-f5502db30123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDkxOTAsIm5iZiI6MTczMzIwODg5MCwicGF0aCI6Ii8xNjE1OTgyNDAvMzkxODQ1NTE1LWZiYjRiOGE4LWNiMGItNDk5Yy1hODYzLWY1NTAyZGIzMDEyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNjU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGE0MWMyYjFhNTM1OWQxMzkxZGEzZDBlZmI4NDQ4OWI2YjAwYTIzMDI1ZGY3Mjk2Y2I5MWQyZjliMjMzZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sl03NZYZG02HKaxPVUc5H4wXZF0G2D2_Lch5f32wcA8)
