### ISSUE TITLE
yeying首页重要信息补充

### ISSUE THREAD

**Issue by zzzjy88** [yeying-community/yeying-next#3]
1、域名：夜莺社区
2、工信部备案号浙ICP备2024126729号-2跳转链接https://beian.miit.gov.cn
3、联系邮箱：[yeying.community@gmail.com]
4、右下角小红书链接
https://www.xiaohongshu.com/user/profile/656ddc960000000020031366?xhsshare=WeixinSession&appuid=656ddc960000000020031366&apptime=1732503950&share_id=0d65734da9264065b28e61c93f220371

**Comment by zjlzlr** [comment]
已解决
